import React, { useState } from 'react';
import { usePermissions } from '../../context/PermissionContext';
import { StatCard } from '../../components/common/StatCard';
import { DataTable } from '../../components/common/DataTable';
import { Drawer } from '../../components/common/Drawer';
import { StatusBadge } from '../../components/common/StatusBadge';
import {
  REPORT_TEMPLATES,
  INITIAL_GENERATION_HISTORY
} from '../../services/mock/mockReports';
import {
  FileText,
  Download,
  Play,
  Eye,
  Calendar,
  CheckCircle2,
  Clock,
  Filter,
  RefreshCw,
  Layers,
  Database,
  ShieldCheck
} from 'lucide-react';

export const ReportsPage = () => {
  const { can } = usePermissions();
  const [selectedTemplate, setSelectedTemplate] = useState(null);
  const [categoryFilter, setCategoryFilter] = useState('ALL');
  const [generatingId, setGeneratingId] = useState(null);
  const [generationHistory, setGenerationHistory] = useState(INITIAL_GENERATION_HISTORY);
  const [successToast, setSuccessToast] = useState(null);

  const filteredTemplates = REPORT_TEMPLATES.filter((tpl) => {
    if (categoryFilter === 'ALL') return true;
    return tpl.category === categoryFilter;
  });

  const handleGenerateReport = (template) => {
    setGeneratingId(template.id);
    setTimeout(() => {
      setGeneratingId(null);
      const newEntry = {
        id: `gen-${Date.now()}`,
        templateTitle: template.title,
        generatedBy: 'You (Active Session)',
        timestamp: new Date().toISOString().replace('T', ' ').substring(0, 16),
        records: template.recordsCount,
        fileSize: `${(Math.random() * 1.5 + 0.5).toFixed(1)} MB`,
        format: template.format.split('/')[0].trim(),
        status: 'READY'
      };
      setGenerationHistory((prev) => [newEntry, ...prev]);
      setSuccessToast(`Report "${template.title}" generated successfully!`);
      setTimeout(() => setSuccessToast(null), 4000);
    }, 1000);
  };

  const handleDownloadReport = (title, format) => {
    const link = document.createElement('a');
    link.setAttribute('href', 'data:text/plain;charset=utf-8,TruckMitr Enterprise Report: ' + title);
    link.setAttribute('download', `${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const historyColumns = [
    {
      key: 'templateTitle',
      title: 'Report Title',
      sortable: true,
      render: (_, row) => (
        <div style={{ fontWeight: 600, color: '#0F172A' }}>{row.templateTitle}</div>
      )
    },
    {
      key: 'generatedBy',
      title: 'Generated By',
      sortable: true,
      render: (_, row) => (
        <div style={{ fontSize: '12px', color: '#64748B' }}>{row.generatedBy}</div>
      )
    },
    {
      key: 'timestamp',
      title: 'Timestamp',
      sortable: true,
      render: (_, row) => (
        <div style={{ fontSize: '12px', color: '#64748B' }}>{row.timestamp}</div>
      )
    },
    {
      key: 'records',
      title: 'Records',
      sortable: true,
      render: (val) => (
        <span style={{ fontWeight: 700, color: '#1467FF' }}>{val} rows</span>
      )
    },
    {
      key: 'format',
      title: 'Format & Size',
      render: (_, row) => (
        <span style={{ fontSize: '12px', color: '#334155' }}>
          {row.format} ({row.fileSize})
        </span>
      )
    },
    {
      key: 'status',
      title: 'Status',
      render: (val) => <StatusBadge status={val} variant="success" />
    },
    {
      key: 'actions',
      title: 'Actions',
      render: (_, row) => (
        <button
          onClick={() => handleDownloadReport(row.templateTitle, row.format)}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            padding: '6px 12px',
            borderRadius: '6px',
            border: '1px solid #E2E8F0',
            backgroundColor: '#FFFFFF',
            color: '#1467FF',
            fontSize: '12px',
            fontWeight: 600,
            cursor: 'pointer'
          }}
        >
          <Download size={14} /> Download
        </button>
      )
    }
  ];

  return (
    <div style={{ padding: '24px', maxWidth: '1440px', margin: '0 auto' }}>
      {/* Success Notification */}
      {successToast && (
        <div
          style={{
            position: 'fixed',
            bottom: '24px',
            right: '24px',
            backgroundColor: '#0F172A',
            color: '#FFFFFF',
            padding: '14px 20px',
            borderRadius: '10px',
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            boxShadow: '0 10px 25px rgba(0,0,0,0.2)',
            zIndex: 1000,
            borderLeft: '4px solid #10B981',
            fontSize: '13px',
            fontWeight: 600
          }}
        >
          <CheckCircle2 size={18} color="#10B981" />
          <span>{successToast}</span>
        </div>
      )}

      {/* Header Banner */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          marginBottom: '24px',
          flexWrap: 'wrap',
          gap: '16px'
        }}
      >
        <div>
          <h1 style={{ fontSize: '24px', fontWeight: 800, color: '#0F172A', margin: 0 }}>
            Enterprise Reports Hub
          </h1>
          <p style={{ color: '#64748B', fontSize: '14px', margin: '4px 0 0' }}>
            Catalog of standardized reports generated dynamically from live operational, financial, and HR data sources.
          </p>
        </div>
      </div>

      {/* KPI StatCards */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
          gap: '16px',
          marginBottom: '24px'
        }}
      >
        <StatCard
          title="Report Templates Available"
          value={REPORT_TEMPLATES.length.toString()}
          change="Across 4 Departments"
          isPositive={true}
          iconColor="#1467FF"
          iconBg="#EFF6FF"
          icon={FileText}
        />
        <StatCard
          title="Automated Scheduled Runs"
          value="6 Active"
          change="Daily/Weekly Auto-Sync"
          isPositive={true}
          iconColor="#10B981"
          iconBg="#ECFDF5"
          icon={Clock}
        />
        <StatCard
          title="Reports Generated Today"
          value={generationHistory.length.toString()}
          change="All Systems Healthy"
          isPositive={true}
          iconColor="#059669"
          iconBg="#ECFDF5"
          icon={Database}
        />
        <StatCard
          title="Data Security Audit"
          value="100% Gated"
          change="RBAC Enforced per Role"
          isPositive={true}
          iconColor="#8B5CF6"
          iconBg="#F3E8FF"
          icon={ShieldCheck}
        />
      </div>

      {/* Category Filter */}
      <div
        style={{
          display: 'flex',
          gap: '10px',
          marginBottom: '20px',
          flexWrap: 'wrap',
          alignItems: 'center'
        }}
      >
        <span style={{ fontSize: '13px', fontWeight: 600, color: '#475569' }}>Filter by Department:</span>
        {['ALL', 'Finance', 'Operations', 'People & HR', 'CRM & Sales'].map((cat) => (
          <button
            key={cat}
            onClick={() => setCategoryFilter(cat)}
            style={{
              padding: '6px 14px',
              borderRadius: '20px',
              border: 'none',
              fontSize: '12px',
              fontWeight: 700,
              backgroundColor: categoryFilter === cat ? '#1467FF' : '#F1F5F9',
              color: categoryFilter === cat ? '#FFFFFF' : '#475569',
              cursor: 'pointer',
              transition: 'all 0.15s'
            }}
          >
            {cat === 'ALL' ? 'All Templates' : cat}
          </button>
        ))}
      </div>

      {/* Report Templates Grid */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
          gap: '20px',
          marginBottom: '32px'
        }}
      >
        {filteredTemplates.map((tpl) => {
          const isGenerating = generatingId === tpl.id;
          return (
            <div
              key={tpl.id}
              style={{
                backgroundColor: '#FFFFFF',
                borderRadius: '12px',
                padding: '20px',
                border: '1px solid #E2E8F0',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'space-between',
                boxShadow: '0 1px 3px rgba(0,0,0,0.05)'
              }}
            >
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
                  <span
                    style={{
                      fontSize: '11px',
                      fontWeight: 700,
                      padding: '3px 8px',
                      borderRadius: '6px',
                      backgroundColor: '#EFF6FF',
                      color: '#1E40AF'
                    }}
                  >
                    {tpl.category}
                  </span>
                  <span style={{ fontSize: '11px', color: '#64748B', fontWeight: 500 }}>
                    {tpl.format}
                  </span>
                </div>

                <h3 style={{ fontSize: '16px', fontWeight: 700, color: '#0F172A', margin: '0 0 8px' }}>
                  {tpl.title}
                </h3>
                <p style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5', margin: '0 0 16px' }}>
                  {tpl.description}
                </p>

                <div
                  style={{
                    backgroundColor: '#F8FAFC',
                    borderRadius: '8px',
                    padding: '10px 12px',
                    fontSize: '12px',
                    color: '#475569',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '4px',
                    marginBottom: '16px'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#64748B' }}>Source Module:</span>
                    <span style={{ fontWeight: 600, color: '#1467FF' }}>{tpl.sourceModule.toUpperCase()}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#64748B' }}>Cadence:</span>
                    <span style={{ fontWeight: 500 }}>{tpl.schedule}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: '#64748B' }}>Last Run:</span>
                    <span style={{ fontWeight: 500 }}>{tpl.lastGenerated}</span>
                  </div>
                </div>
              </div>

              <div style={{ display: 'flex', gap: '8px', borderTop: '1px solid #F1F5F9', paddingTop: '14px' }}>
                <button
                  onClick={() => setSelectedTemplate(tpl)}
                  style={{
                    flex: 1,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '6px',
                    padding: '8px 12px',
                    backgroundColor: '#FFFFFF',
                    border: '1px solid #CBD5E1',
                    borderRadius: '6px',
                    fontSize: '12px',
                    fontWeight: 600,
                    color: '#334155',
                    cursor: 'pointer'
                  }}
                >
                  <Eye size={14} /> Preview
                </button>

                {can('reports', 'create') && (
                  <button
                    onClick={() => handleGenerateReport(tpl)}
                    disabled={isGenerating}
                    style={{
                      flex: 1,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '6px',
                      padding: '8px 12px',
                      backgroundColor: '#1467FF',
                      color: '#FFFFFF',
                      border: 'none',
                      borderRadius: '6px',
                      fontSize: '12px',
                      fontWeight: 700,
                      cursor: isGenerating ? 'not-allowed' : 'pointer',
                      opacity: isGenerating ? 0.7 : 1
                    }}
                  >
                    {isGenerating ? (
                      <>
                        <RefreshCw size={14} className="animate-spin" /> Generating...
                      </>
                    ) : (
                      <>
                        <Play size={14} /> Generate
                      </>
                    )}
                  </button>
                )}

                {can('reports', 'export') && (
                  <button
                    onClick={() => handleDownloadReport(tpl.title, tpl.format)}
                    style={{
                      padding: '8px 12px',
                      backgroundColor: '#F8FAFC',
                      border: '1px solid #CBD5E1',
                      borderRadius: '6px',
                      color: '#475569',
                      cursor: 'pointer'
                    }}
                    title="Quick Download"
                  >
                    <Download size={14} />
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Generation Run History Section */}
      <div style={{ backgroundColor: '#FFFFFF', borderRadius: '12px', padding: '20px', border: '1px solid #E2E8F0' }}>
        <h3 style={{ fontSize: '16px', fontWeight: 700, color: '#0F172A', marginTop: 0, marginBottom: '16px' }}>
          Recent Report Generation Runs
        </h3>
        <DataTable columns={historyColumns} data={generationHistory} searchable={false} pagination={false} />
      </div>

      {/* Report Preview Drawer */}
      <Drawer
        isOpen={Boolean(selectedTemplate)}
        onClose={() => setSelectedTemplate(null)}
        title={selectedTemplate ? `Report Preview: ${selectedTemplate.title}` : ''}
      >
        {selectedTemplate && (
          <div>
            <div
              style={{
                padding: '12px 16px',
                backgroundColor: '#EFF6FF',
                borderRadius: '8px',
                marginBottom: '16px',
                fontSize: '12px',
                color: '#1E40AF',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center'
              }}
            >
              <span>
                Showing live underlying records from <strong>{selectedTemplate.sourceModule.toUpperCase()}</strong> module
              </span>
              <span style={{ fontWeight: 700 }}>{selectedTemplate.recordsCount} Rows</span>
            </div>

            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12px' }}>
                <thead>
                  <tr style={{ borderBottom: '2px solid #CBD5E1', backgroundColor: '#F8FAFC', textAlign: 'left' }}>
                    {selectedTemplate.previewHeaders.map((hdr, i) => (
                      <th key={i} style={{ padding: '8px 10px', fontWeight: 700, color: '#334155' }}>
                        {hdr}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {selectedTemplate.getPreviewData().map((row, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid #F1F5F9' }}>
                      <td style={{ padding: '8px 10px', fontWeight: 600, color: '#1467FF' }}>{row.id}</td>
                      <td style={{ padding: '8px 10px', color: '#0F172A' }}>{row.col1}</td>
                      <td style={{ padding: '8px 10px', color: '#475569' }}>{row.col2}</td>
                      <td style={{ padding: '8px 10px', fontWeight: 600 }}>{row.col3}</td>
                      <td style={{ padding: '8px 10px' }}>
                        <span
                          style={{
                            padding: '2px 6px',
                            borderRadius: '4px',
                            backgroundColor: '#F1F5F9',
                            fontSize: '11px',
                            fontWeight: 600
                          }}
                        >
                          {row.col4}
                        </span>
                      </td>
                      <td style={{ padding: '8px 10px', color: '#64748B' }}>{row.date}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {can('reports', 'export') && (
              <div style={{ marginTop: '20px', borderTop: '1px solid #E2E8F0', paddingTop: '16px' }}>
                <button
                  onClick={() => handleDownloadReport(selectedTemplate.title, selectedTemplate.format)}
                  style={{
                    width: '100%',
                    padding: '10px',
                    backgroundColor: '#1467FF',
                    color: '#FFFFFF',
                    border: 'none',
                    borderRadius: '8px',
                    fontWeight: 700,
                    fontSize: '13px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '8px',
                    cursor: 'pointer'
                  }}
                >
                  <Download size={16} /> Download Full Dataset ({selectedTemplate.format})
                </button>
              </div>
            )}
          </div>
        )}
      </Drawer>
    </div>
  );
};
